Algoritmo "semnome"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 13/09/2021
Var
M, Mc, F :inteiro
S :Caracter
Inicio
F<-0
M<-0
Escreva("Digite os sexos ")
leia(S)
   se S=M entao
   M<-1
   enquanto S=M faca
   Mc<-M+1
   fimenquanto

         fimse
escreval("Masculino: ", Mc)
escreval("Feminino: ",F)

Fimalgoritmo